### ISSUE TITLE
Termo de Abertura do Projeto (TAP)

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IDotPet#11]
# Descrição:

Essa issue tem como objetivo elaborar o documento do Termo de Abertura do Projeto.

# Pré-requisitos:

- [x] Não há pré-requisitos.

# Tarefas:

- [x] Produzir o Termo de Abertura do Projeto (TAP)
- [x] Revisar o documento TAP.

# Critério de aceitação:

- [x] Termo de Abertura do Projeto elaborado.
- [x] Termo de Abertura do Projeto revisador.

**Comment by klyssmannoliveira** [comment]
Link para iniciar a elaboração do artefato: [Estimativas](https://unbbr-my.sharepoint.com/:v:/g/personal/mileneserrano_unb_br/EQvzWZwb9llHjmuA0XrEAJ4BPdH0irPT8XMP6ZFN1iFUXA?e=HUMr5L)

**Comment by klyssmannoliveira** [comment]
Artefato concluído com sucesso.
