### ISSUE TITLE
Frontend - Cadastro

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IdotPet#127]
# Descrição:

Issue dedicada a trabalhar no frontend da página de cadastro.

# Tarefas:

- [x] Trabalhar no frontend da tela de cadastro

# Critério de aceitação:

- [x] Tela de cadastro finalizada

**Comment by Luan-Cavalcante** [comment]
Cadastro de usuário concluída.
