### ISSUE TITLE
Organização do repositório GitHub

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IDotPet#15]
# Descrição:

Essa issue tem como objetivo organizar o repositório GitHub do projeto.

# Pré-requisitos:

- [x] Não há pré-requisitos.

# Tarefas:

- [x] Definir política de organização do repositório.
- [x] Organizar o repositório GitHub do projeto.

# Critério de aceitação:

- [ ]  Política de organização do repositório definida .
- [x] Repositório do projeto organizado.

**Comment by PedroLucasCM** [comment]
Issue resolvida, qualquer mudança será criada outra!
