### ISSUE TITLE
Acompanhamento do Design Sprint

### ISSUE THREAD

**Issue by PedroLucasCM** [UnBArqDsw2022-2/2022.2_G4_IDotPet#23]
# Descrição:

Essa issue tem como objetivo acompanhar o processo do Design Sprint.

1. Unpack: 
   - [x] Brainstorming
   - [x] Mapas mentais
2. Sketch:
   - [x] Rich Pictures
3. Decision:
   - [x] Escolha do melhor Rich Picture
   - [x] Storyboard
4. Prototype
   - [x] Protótipo
 
# Pré-requisitos:

- [x] #5
- [x] #6  
- [x] #24
- [x] #10

# Tarefas:

- [x] Elaboração dos documentos listados no pré-requisitos.
- [x] Cumprimento das atividades propostas pela Design Sprint

# Critério de aceitação:

- [x] Mapa mental de acordo com o brainstorming
- [x] Rich Picture de acordo com o Mapa mental
- [x] Storyboard de acordo com o Rich Picture
- [x] Protótipo de acordo com o Storyboard

**Comment by victordscabral** [comment]
Issue finalizada.
