### ISSUE TITLE
Storyboard

### ISSUE THREAD

**Issue by PedroLucasCM** [UnBArqDsw2022-2/2022.2_G4_IDotPet#24]
# Descrição:

Essa issue tem como objetivo criar um Storyboard de como o app será usado pelo usuário. 
 
# Pré-requisitos:

- [x] #6 

# Tarefas:

- [x] Criação do Storyboard

# Critério de aceitação:

- [x] Storyboard completo de acordo com o Rich Picture e o Protótipo

**Comment by PedroLucasCM** [comment]
@hericklima22 @Nicolas-Roberto Ajudem eles se precisarem, por favor.

**Comment by victordscabral** [comment]
Issue finalizada.
