### ISSUE TITLE
Organização do Repositório GitHub - Parte 2

### ISSUE THREAD

**Issue by PedroLucasCM** [UnBArqDsw2022-2/2022.2_G4_IDotPet#34]
# Descrição:

Essa issue tem como objetivo organizar o repositório GitHub do projeto.

# Pré-requisitos:

- [x] Não há pré-requisitos.

# Tarefas:

- [x] Definir política de organização do repositório.
- [x] Organizar o repositório GitHub do projeto.

# Critério de aceitação:

- [x]  Política de organização do repositório definida .
- [x] Repositório do projeto organizado.

**Comment by victordscabral** [comment]
Issue finalizada.
