### ISSUE TITLE
Documento de Brainstorm

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IDotPet#40]
# Descrição:

Essa issue tem como objetivo criar o documento constando informações do brainstorming feito pela equipe, além das imagens do resultado do próprio (mapa mental).

# Pré-requisitos:

- [x] #5.

# Tarefas:

- [ ] Criar documento de brainstorming.
- [ ] Constar informações do que ocorreu no dia.
- [ ] Adicionar imagens dos mapas mentais elaborados.

# Critério de aceitação:

- [ ] Documento do brainstorming criado.
- [ ] Informações do que ocorreu no dia constadas.
- [ ] Imagens dos mapas mentais adicionadas.

**Comment by klyssmannoliveira** [comment]
Issue finalizada
