### ISSUE TITLE
Diagrama de Classes

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IDotPet#54]
# Descrição:

Essa issue tem como objetivo a elaboração do documento de Diagrama de Classes.

# Tarefas:

- [x] Elaborar Diagrama de Classes (Pedro e Herick)
- [ ] Revisar Diagrama de Classes (Klyssmann e Victor e Nicolas)

# Critério de aceitação:

- [ ] Histórico de versões do diagrama (evolução)
- [ ] Documento de Diagrama de Classes confeccionado.
- [ ] Documento de Diagrama de Classes revisado.

**Comment by klyssmannoliveira** [comment]
Issue Finalizada!

**Comment by victordscabral** [comment]
Issue finalizada.
