### ISSUE TITLE
Diagrama de Estados

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IDotPet#60]
# Descrição:

Essa issue tem como objetivo a elaboração do documento de Diagrama de Estados.

# Tarefas:

- [x] Elaborar Diagrama de Estados (Pedro e Herick)
- [x] Revisar Diagrama de Estados (Eduardo e Kayro)

# Critério de aceitação:

- [x] Documento de Diagrama de Estados confeccionado.
- [x] Documento de Diagrama de Estados revisado.

**Comment by PedroLucasCM** [comment]
Diagrama de Estados feito, revisado e aprovado!
