### ISSUE TITLE
Diagrama de Atividades

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IDotPet#61]
# Descrição:

Essa issue tem como objetivo a elaboração do documento de Diagrama de Atividades.

# Tarefas:

- [x] Elaborar Diagrama de Atividades (Luan e Thalisson)
- [ ] Revisar Diagrama de Atividades (Pedro e Herick)

# Critério de aceitação:

- [x] Documento de Diagrama de Atividades confeccionado.
- [x] Documento de Diagrama de Atividades revisado.

**Comment by PedroLucasCM** [comment]
Documento revisado, bem documentado!
