### ISSUE TITLE
DDD (Domain Drive Design)

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IDotPet#64]
# Descrição:

Essa issue tem como objetivo a elaboração do documento de DDD.

# Tarefas:

- [x] Elaborar DDD (Vitor e Durso)
- [ ] Revisar DDD (Pedro e Herick)

# Critério de aceitação:

- [ ] Documento de DDD confeccionado.
- [ ] Documento de DDD revisado.

**Comment by klyssmannoliveira** [comment]
Issue finalizada
