### ISSUE TITLE
Correção do BPMN

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IDotPet#65]
# Descrição:

Essa issue tem como objetivo corrigir o BPMN conforme recomendações da apresentação base.

# Tarefas:

- [ ] Revisar BPMN (Pedro, Victor, Klyssmann)

# Critério de aceitação:

- [ ] Documento de BPMN revisado.

**Comment by klyssmannoliveira** [comment]
Issue finalizada
