### ISSUE TITLE
Correção do Léxico

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IDotPet#66]
# Descrição:

Essa issue tem como objetivo corrigir o Léxico conforme recomendações da apresentação base.

# Tarefas:

- [x] Revisar e corrigir Léxico (Nicolas e Herick)
- [x]  Alterar nomes da  noção e impacto da classe objeto (Nicolas e Herick)
- [x] Dividir usando as classe como divisor (Nicolas e Herick)
- [ ] Aumentar o número de impactos (Nicolas e Herick)

# Critério de aceitação:

- [ ] Documento de Léxico revisado e corrigido.

**Comment by klyssmannoliveira** [comment]
Issue Finalizada!

**Comment by victordscabral** [comment]
Issue finalizada.
