### ISSUE TITLE
Melhoria do Backlog do produto

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IdotPet#76]
# Descrição:

Essa issue tem como objetivo a melhoria e adição de mais informações no documento de Backlog do Produto.

# Tarefas:

- [x] Melhoria do Backlog do Produto (Klyssmann e Victor e Nicolas)
- [ ] Revisar o Backlog do Produto (Vitor e durso)

# Critério de aceitação:

- [x] Documento de Backlog do Produto melhorado.
- [ ] Documento de Backlog do Produto revisado.

**Comment by klyssmannoliveira** [comment]
Issue concluída
