### ISSUE TITLE
Arquivo de Apresentação - Modelagem

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IdotPet#84]
# Descrição:

Preparar o arquivo de entrega para o módulo MODELAGEM. 
 
# Pré-requisitos:

Não há pré-requisitos.

# Tarefas:

- [x] documento em pdf com a identificação do grupo, nome do projeto e detalhamento dos membros da equipe do projeto;
- [x] link para o repositório do projeto;
- [x] Breve relato sobre as participações/contribuições de cada membro à entrega. 

# Critério de aceitação:

- [x] Arquivo único (ZIP)

**Comment by klyssmannoliveira** [comment]
![image](https://user-images.githubusercontent.com/56873266/205521676-30c21282-6dfe-4d75-b900-07a6e2da38c9.png)
Issue Finalizada
