### ISSUE TITLE
Estudos: Padrão Emergente

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IdotPet#94]
# Descrição:

Essa issue tem como objetivo realizar estudos sobre o Padrão Emergente, atividade necessária para a próxima entrega da equipe. Os responsáveis pela atividade devem entender a atividade que deve ser realizada, comentando na issue com materiais sobre conteúdo estudado e boas referências que podem ser seguidas.

Obs.: 
- Peço que essa issue não seja ignorada.
- Os responsáveis são bem vindos a já começar o desenvolvimento do artefato se possível.
 
# Pré-requisitos:

Não há pré-requisitos.

# Tarefas:

- [x] Entender bem o artefato que deve ser desenvolvido;
- [x] Postar materiais que serão seguidos como base para a elaboração do artefato;
- [x] Postar boas referências do artefato.

# Critério de aceitação:

- [ ] Artefato bem entendido;
- [x] Materiais postados;
- [x] Referências postadas

**Comment by victordscabral** [comment]
Sites para estudo: 
https://www.devmedia.com.br/introducao-design-pattern/18838
https://www.devmedia.com.br/design-patterns-padroes-gof/16781

Recomendação: estudar material da professora!

**Comment by PedroLucasCM** [comment]
É necessário criar uma wiki com os padrões de projeto *mais* emergentes associados a plataforma e tecnologias da atualidade.
Para isso precisamos entender o que é um padrão de projeto. Eu nao sei o que é. Irei estudar.

**Comment by PedroLucasCM** [comment]
Padrões de Projeto são princípios e soluções, documentados bem estruturados descrevendo um problema e sua solução adotada pela equipe de projeto.
Temos 2 tipos de padrões de projetos que se ramificam em diversas tipos especializados.
Os 2 tipos são:
Grasp (Padrões de Software para Atribuições de Responsabilidade Geral) e
GoFs (Gang of Fours);

A Equipe irá explicar mais sobre esses tipos de padrões de projeto.

**Comment by PedroLucasCM** [comment]
Agora é encontrar aplicações, plataformas e tecnologias da atualidade  que utilizam padrões de projeto mais emergentes

**Comment by PedroLucasCM** [comment]
https://unbarqdsw.github.io/2020.1_G6_Pomo/padrões-de-projeto/modulo3.5/padroes_emergentes/
https://unbarqdsw2022-1.github.io/2022_1_G5_SerFit/#/PadroesDeProjeto/PadroesEmergentes/capaEmergente

**Comment by PedroLucasCM** [comment]
@klyssmannoliveira @hericklima22 deem uma olhada ai nos materias de base e na explicação, ai vocês fechem ai a issue

**Comment by eduardomr** [comment]
Padrões de projeto utilizados nas tecnologias que serão adotadas no projeto: 
https://blog.flutterando.com.br/implementando-padr%C3%B5es-de-projetos-em-dart-parte-1-d604f6038460
https://www.devmedia.com.br/conheca-os-padroes-de-projeto/957

**Comment by eduardomr** [comment]
Padrão MVC: https://www.geeksforgeeks.org/mvc-design-pattern/

**Comment by victordscabral** [comment]
Finalizada.
