### ISSUE TITLE
 Estudos: GoFs - Criacionais

### ISSUE THREAD

**Issue by victordscabral** [UnBArqDsw2022-2/2022.2_G4_IdotPet#98]
# Descrição:

Essa issue tem como objetivo realizar estudos sobre o GoFs - Criacionais, atividade necessária para a próxima entrega da equipe. Os responsáveis pela atividade devem entender a atividade que deve ser realizada, comentando na issue com materiais sobre conteúdo estudado e boas referências que podem ser seguidas.

Obs.: 
- Peço que essa issue não seja ignorada.
- Os responsáveis são bem vindos a já começar o desenvolvimento do artefato se possível.
 
# Pré-requisitos:

Não há pré-requisitos.

# Tarefas:

- [ ] Entender bem o artefato que deve ser desenvolvido;
- [ ] Postar materiais que serão seguidos como base para a elaboração do artefato;
- [ ] Postar boas referências do artefato.

# Critério de aceitação:

- [ ] Artefato bem entendido;
- [ ] Materiais postados;
- [ ] Referências postadas

**Comment by victordscabral** [comment]
Exemplo de repositório para estudo: https://unbarqdsw2022-1.github.io/2022_1_G5_SerFit/#/PadroesDeProjeto/GoFs/capaGofs

**Comment by victordscabral** [comment]
Site para estudo: https://www.devmedia.com.br/design-patterns-padroes-gof/16781

**Comment by victordscabral** [comment]
![image](https://user-images.githubusercontent.com/87657291/206939964-60814e49-75bb-4d64-8ce2-9253ade7c30d.png)
![image](https://user-images.githubusercontent.com/87657291/206939976-3e0aeb89-a848-4db8-982d-4ddd51d6b164.png)

O Factory Method e Abstract Factory são essenciais. O ideal é implementar a maior parte  dos citados na imagem.

**Comment by kayrocesar** [comment]
Mais um exemplo de repositório sobre GOFs criacionais: 
https://unbarqdsw.github.io/2020.1_G7_TCM/docs/padroesProjeto/gofs_criacionais

**Comment by victordscabral** [comment]
Finalizada.
